services:
  api:
    build: .
    entrypoint: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: rag-api
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - VECTOR_DB_URL=http://qdrant:6333
      - OLLAMA_BASE_URL=http://ollama:11434
      - EMBED_URL=http://embed-server:8080
      - RERANK_URL=http://rerank-server:8080
    depends_on:
      - qdrant
      - ollama
      - embed-server
      - rerank-server
    volumes:
      - .:/app

  embed-server:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    container_name: embed-server
    command: --model-id BAAI/bge-m3 --port 8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./models/tei-embed:/model

  rerank-server:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    container_name: rerank-server
    command: --model-id BAAI/bge-reranker-v2-m3 --port 8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./models/tei-rerank:/model
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: ollama-server
    volumes:
      - ./models/ollama:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  qdrant_storage: